# Generated by Django 4.0 on 2022-02-14 01:34

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Chat id пользователя')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=64, verbose_name='Ник пользователя')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 2, 14, 1, 34, 59, 182894, tzinfo=utc), verbose_name='Дата создания')),
                ('last_use', models.DateTimeField(default=datetime.datetime(2022, 2, 14, 1, 34, 59, 182934, tzinfo=utc), verbose_name='Дата последнего использования')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('sex', models.CharField(blank=True, max_length=1, verbose_name='Пол')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='О себе')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Анкета зарегистрирована?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Анкета активна?')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProfileLikes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('unviewed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('viewed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Профиль для лайков',
                'verbose_name_plural': 'Профили для лайков',
            },
        ),
        migrations.CreateModel(
            name='ProfileSearch',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('age', models.CharField(default='13-100', max_length=10, verbose_name='Возраст собеседника')),
                ('sex', models.CharField(default='A', max_length=1, verbose_name='Пол собеседника')),
                ('unviewed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('viewed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Профиль для поиска',
                'verbose_name_plural': 'Профили для поиска',
            },
        ),
    ]
