# Generated by Django 4.0 on 2022-02-14 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Chat id пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 44, 31, 424221, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 44, 31, 424257, tzinfo=utc), verbose_name='Дата последнего использования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Ник пользователя'),
        ),
    ]
