# Generated by Django 4.0 on 2022-02-14 20:54

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_user_chat_id_alter_user_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelikes',
            name='unviewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None, verbose_name='не просмотренные лайки'),
        ),
        migrations.AlterField(
            model_name='profilelikes',
            name='viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None, verbose_name='взаимные лайки'),
        ),
        migrations.AlterField(
            model_name='profilesearch',
            name='unviewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profilesearch',
            name='viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Chat id пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 20, 54, 13, 51186, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 20, 54, 13, 51186, tzinfo=utc), verbose_name='Дата последнего использования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ник пользователя'),
        ),
    ]
