# Generated by Django 4.0 on 2022-02-14 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_profilelikes_unviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 20, 57, 43, 914251, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 20, 57, 43, 914251, tzinfo=utc), verbose_name='Дата последнего использования'),
        ),
    ]
