# Generated by Django 4.0 on 2022-02-15 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_user_creation_date_alter_user_last_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 14, 44, 56, 865353, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 14, 44, 56, 865393, tzinfo=utc), verbose_name='Дата последнего использования'),
        ),
    ]
