# Generated by Django 4.0 on 2022-02-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_user_creation_date_alter_user_last_use_and_more'),
        ('tgbot', '0006_alter_user_creation_date_alter_user_last_use'),
    ]

    operations = [
    ]
