# Generated by Django 4.0 on 2022-02-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_alter_user_creation_date_alter_user_last_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActType',
            fields=[
                ('type', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Название типа действия')),
            ],
        ),
        migrations.CreateModel(
            name='LogUsers',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('log_date', models.DateTimeField(auto_now=True, verbose_name='Дата совершения действия')),
                ('description', models.CharField(max_length=400, verbose_name='Дополнительные данные о действии')),
                ('act_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.acttype', verbose_name='Название типа действия')),
            ],
        ),
    ]
