# Generated by Django 4.0 on 2022-02-23 00:21

from django.db import migrations

def create_type_table(apps, schema_editor):
    ActType = apps.get_model("tgbot", "ActType")
    # ActType.objects.create(type="start")
    # ActType.objects.create(type="name")
    # ActType.objects.create(type="age")
    # ActType.objects.create(type="sex")
    # ActType.objects.create(type="decr")
    # ActType.objects.create(type="decr")

class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_acttype_logusers'),
    ]

    operations = [
         migrations.RunPython(create_type_table),
    ]
